<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EntrenamientosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('entrenamientos')->insert([
            [
                'idValoracion' => null,
                'nombre' => 'Entrenamiento de fuerza',
                'descripcion' => 'Rutina centrada en ejercicios con sobrecarga progresiva para aumentar la masa muscular y la fuerza máxima. Trabaja todos los grupos musculares principales.',
                'objetivo' => 'Incrementar la fuerza y la hipertrofia muscular.',
                'duracion' => 60,
                'nivel' => 'Intermedio',
                'diasSemana' => 4,
                'estado' => 'Activo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idValoracion' => null,
                'nombre' => 'Entrenamiento funcional',
                'descripcion' => 'Sesión que utiliza movimientos naturales de la vida diaria para mejorar la fuerza, el equilibrio y la coordinación general del cuerpo.',
                'objetivo' => 'Mejorar la capacidad física para actividades diarias y prevenir lesiones.',
                'duracion' => 45,
                'nivel' => 'Principiante',
                'diasSemana' => 3,
                'estado' => 'Activo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idValoracion' => null,
                'nombre' => 'Entrenamiento cardiovascular',
                'descripcion' => 'Ejercicios de ritmo constante como correr, nadar o usar la elíptica para mejorar la salud del corazón y la resistencia pulmonar.',
                'objetivo' => 'Aumentar la capacidad aeróbica y la resistencia cardiovascular.',
                'duracion' => 40,
                'nivel' => 'Principiante',
                'diasSemana' => 3,
                'estado' => 'Activo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idValoracion' => null,
                'nombre' => 'Entrenamiento de resistencia',
                'descripcion' => 'Programa diseñado para aumentar la capacidad de los músculos para realizar esfuerzo durante períodos prolongados sin fatigarse.',
                'objetivo' => 'Mejorar la resistencia muscular y cardiovascular.',
                'duracion' => 50,
                'nivel' => 'Intermedio',
                'diasSemana' => 4,
                'estado' => 'Activo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idValoracion' => null,
                'nombre' => 'Entrenamiento HIIT (High Intensity Interval Training)',
                'descripcion' => 'Sesiones de ráfagas de ejercicio de máxima intensidad alternadas con períodos de descanso cortos. Máxima quema de calorías en poco tiempo.',
                'objetivo' => 'Optimizar la quema de grasa y mejorar la capacidad anaeróbica.',
                'duracion' => 30,
                'nivel' => 'Avanzado',
                'diasSemana' => 3,
                'estado' => 'Activo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idValoracion' => null,
                'nombre' => 'Entrenamiento con pesas libres',
                'descripcion' => 'Uso de barras, mancuernas y discos para realizar ejercicios de fuerza. Permite un rango de movimiento natural y trabaja músculos estabilizadores.',
                'objetivo' => 'Desarrollar fuerza funcional y masa muscular de forma equilibrada.',
                'duracion' => 55,
                'nivel' => 'Intermedio',
                'diasSemana' => 4,
                'estado' => 'Activo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idValoracion' => null,
                'nombre' => 'Entrenamiento en máquinas',
                'descripcion' => 'Rutina guiada usando máquinas de gimnasio. Ideal para principiantes ya que marcan el recorrido y reducen el riesgo de lesión.',
                'objetivo' => 'Fortalecer grupos musculares específicos de forma segura.',
                'duracion' => 50,
                'nivel' => 'Principiante',
                'diasSemana' => 3,
                'estado' => 'Activo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idValoracion' => null,
                'nombre' => 'Entrenamiento de core',
                'descripcion' => 'Ejercicios enfocados en fortalecer los músculos del abdomen, espalda baja y pelvis. Fundamental para la estabilidad y la postura.',
                'objetivo' => 'Mejorar la estabilidad del tronco y prevenir dolores de espalda.',
                'duracion' => 25,
                'nivel' => 'Intermedio',
                'diasSemana' => 4,
                'estado' => 'Activo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idValoracion' => null,
                'nombre' => 'Entrenamiento de potencia',
                'descripcion' => 'Ejercicios explosivos como levantamientos olímpicos o saltos para mejorar la capacidad de generar fuerza rápidamente.',
                'objetivo' => 'Incrementar la potencia muscular y la velocidad de reacción.',
                'duracion' => 45,
                'nivel' => 'Avanzado',
                'diasSemana' => 3,
                'estado' => 'Activo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idValoracion' => null,
                'nombre' => 'Entrenamiento de flexibilidad',
                'descripcion' => 'Sesión de estiramientos estáticos y dinámicos para mejorar el rango de movimiento de las articulaciones y liberar tensión muscular.',
                'objetivo' => 'Aumentar la flexibilidad y la movilidad articular.',
                'duracion' => 35,
                'nivel' => 'Principiante',
                'diasSemana' => 5,
                'estado' => 'Activo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idValoracion' => null,
                'nombre' => 'Entrenamiento en circuito',
                'descripcion' => 'Serie de ejercicios realizados uno tras otro con descanso mínimo entre ellos. Combina fuerza y cardio de manera muy eficiente.',
                'objetivo' => 'Mejorar la condición física general y la resistencia.',
                'duracion' => 40,
                'nivel' => 'Intermedio',
                'diasSemana' => 3,
                'estado' => 'Activo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idValoracion' => null,
                'nombre' => 'Entrenamiento con peso corporal',
                'descripcion' => 'Utilización del propio peso del cuerpo como resistencia para ejercicios como flexiones, sentadillas y dominadas. No necesita equipo.',
                'objetivo' => 'Desarrollar fuerza funcional y resistencia en cualquier lugar.',
                'duracion' => 45,
                'nivel' => 'Intermedio',
                'diasSemana' => 4,
                'estado' => 'Activo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idValoracion' => null,
                'nombre' => 'Entrenamiento de crossfit',
                'descripcion' => 'Programa de entrenamiento de fuerza y acondicionamiento basado en movimientos funcionales constantemente variados y ejecutados a alta intensidad.',
                'objetivo' => 'Mejorar la capacidad física en los 10 dominios de CrossFit (resistencia, fuerza, flexibilidad, etc.).',
                'duracion' => 60,
                'nivel' => 'Avanzado',
                'diasSemana' => 5,
                'estado' => 'Activo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}